db.interface.class = de.unileipzig.dbpraktikum.cli_interface.db_interface.DBInterfaceImpl

hibernate.connection.driver_class = org.postgresql.Driver
hibernate.connection.url = jdbc:postgresql://localhost:5432/compose-postgres
hibernate.connection.username = compose-postgres
hibernate.connection.password = compose-postgres
hibernate.default_schema = media_store
hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Only validate scheme, do not create tables
hibernate.hbm2ddl.auto=validate
